---
- hosts: all
  become: true
  pre_tasks:
    - name: update repository index (Fedora)
      tags: always
      dnf:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Fedora"

    - name: update repository index (Ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base

- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  gather_facts: true
  vars:
    mysql_root_password: "Password1"
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers

#  ansible-playbook servers.yml
## This playbook would login with the simone user added in ansible.cfg
