- name: install apache and php
  tags: apache
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: change apache port
  tags: apache
  lineinfile:
    path: "{{ apache_port_file }}"
    regexp: '^Listen 80$'
    line: "Listen {{ apache_listen_port }}"
  notify: restart_apache

- name: start and enable apache
  tags: apache
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
  
- name: change e-mail address for admin
  tags: apache,fedora
  lineinfile:
    path: "{{ apache_config_file }}"
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "Fedora"
  notify: restart_apache

- name: copy html file for site
  tags: apache
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644