# - name: install mariadb package (Fedora)
#   tags: fedora,db,mariadb
#   yum:
#     name: mariadb-server
#     state: latest
#   when: ansible_distribution == "Fedora"
  
- name: install mariadb package (Ubuntu)
  tags: ubuntu,db,mariadb
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"


- name: install mariadb package (Fedora)
  tags: fedora,db,mariadb
  yum:
    name:
      - mariadb-server
      - python3-PyMySQL
    state: latest
  when: ansible_distribution == "Fedora"

- name: start mariadb
  service:
    name: mariadb
    enabled: true
    state: started
  when: ansible_distribution == "Fedora"

- name: mysql_root_password
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: root
    check_implicit_admin: true
    password: "{{ mysql_root_password }}"
    host: localhost
  when: ansible_distribution == "Fedora"

- name: remove remote root
  mysql_user:
    check_implicit_admin: true
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: root
    host: "{{ ansible_fqdn }}"
    state: absent
  when: ansible_distribution == "Fedora"
