# - name: install mariadb package (Fedora)
#   tags: fedora,db,mariadb
#   yum:
#     name: mariadb-server
#     state: latest
#   when: ansible_distribution == "Fedora"
  
- name: install mariadb package
  tags: db,mariadb
  package:
    name: 
     - "{{ db_server_package }}"
     - "{{ db_python_package }}"
    state: latest

- name: start mariadb
  tags: db,mariadb
  service:
    name: "{{ db_service }}"
    enabled: true
    state: started
  register: db_result
  notify: show_db_result

- name: db root password
  tags: db,mariadb
  mysql_user:
    login_user: root
    login_password: "{{ db_root_password }}"
    user: root
    check_implicit_admin: true
    password: "{{ db_root_password }}"
    host: localhost

- name: remove remote root
  tags: db,mariadb
  mysql_user:
    check_implicit_admin: true
    login_user: root
    login_password: "{{ db_root_password }}"
    user: root
    host: "{{ ansible_fqdn }}"
    state: absent
